# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run : |                                                                
          docker version                                                       
          docker info   
      - run:                                                                   
          name: test                                                       
          command: |                                                           
            echo "TEST"
  # Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - build
