apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-s3-
spec:
  entrypoint: test-1
  templates:
  - name: test-1
    script:
      image: amazon/aws-cli:2.0.42
      command: [bash]
      source: |
        aws s3api list-buckets --query "Buckets[].Name" --endpoint-url http://localstack:31000
        aws s3 ls --endpoint-url http://localstack:31000 s3://test-bucket
        aws  s3 cp --endpoint-url http://localstack:31000 s3://test-bucket/sample.csv /tmp/sample.csv
        head /tmp/sample.csv
        cat tettst
      env:
      - name: AWS_ACCESS_KEY_ID
        value: "x"
      - name: AWS_SECRET_ACCESS_KEY
        value: "x"
      - name: AWS_DEFAULT_REGION
        value: "ap-northeast-1"
